### ISSUE TITLE
Tracking of type A modes (bans, quiets, etc.)

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#103]

**Comment by Zarthus** [comment]
Just to add on this issue, https://github.com/KittehOrg/KittehIRCClientLib/issues/112 would also apply here, hopefully!

**Comment by mbax** [comment]
Modes `b`, `e`, and `I` are done.

**Comment by mbax** [comment]
:rocket:

**Comment by mbax** [comment]
`q` added. That's a wrap!

:fire:
