### ISSUE TITLE
Permit opting out of native WHO polling.

### ISSUE THREAD

**Issue by Zarthus** [KittehOrg/KittehIRCClientLib#112]
KICL could be made to interface with things that don't need WHO polling or things that do it themselves - helps prevent hitting flood limits on IRCds

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/compare/NuWHO

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/8d50fb7f63a87fce1ec0d9a46eb603ad85597539
