### ISSUE TITLE
Support receiving of WALLOPS.

### ISSUE THREAD

**Issue by Zarthus** [KittehOrg/KittehIRCClientLib#115]
With usermode `+w` you can receive server wallops. A rarely used feature but useful to support nontheless. Some networks use it to advertise events, give their thanks, or to notify of downtime. Network Staff will, on some IRCds, also receive extra wallops of particular events.

Raw message from receiving a wallop:
```
:nick!user@host WALLOPS :message
```

Sending one is as simple as 
```
WALLOPS :message
```
But this does not sound particularly useful, only network staff can send them so the usecase will be... naught.

**Comment by kashike** [comment]
:+1: for adding more oper-related functionality

**Comment by Zarthus** [comment]
aside from wallops and globals, the rest can be covered with numerics and notice-handling, really

**Comment by mbax** [comment]
See #116
