### ISSUE TITLE
Support setting of a default quit message in the builder.

### ISSUE THREAD

**Issue by Zarthus** [KittehOrg/KittehIRCClientLib#117]
KICL currently has no method of specifying a default quit message. I propose KICL to keep track of a default quit message it will use when none is specified. This way the application built on top need only read it from configuration at initialization rather than on shutdown. 

Overall, this process fits better on initialization than on shutdown I feel.

**Comment by kashike** [comment]
:+1: for a way to set a default message in the builder, as well as a `setQuitMessage` method in `Client ` - as well as keeping the `shutdown(String) ` method

**Comment by Zarthus** [comment]
I'd personally call the method `setDefaultQuitMessage`, the idea is that anything can override it, but if nothing is going to - it will use the default.

**Comment by Zarthus** [comment]
My main interest is in quit messages.  If you think other things can benefit from default messages, that the library should handle, go for it.

**Comment by mbax** [comment]
I understand that's your interest. I'm trying to determine if making a one-off addition like this is the best solution to the problem given the other information, and would love input from other folks familiar with the project.

**Comment by mbax** [comment]
```java
enum QuitReason {
    PING_TIMEOUT,
    SIGTERM
}
```

```java
clientBuilder.setQuitReason(QuitReason.SIGTERM, "Oh no, not again");
```

**Comment by kashike** [comment]
@mbax so:
```java
client.setQuitReason(QuitReason.SIGTERM, "Oh no, not again");
```
```java
builder.quitReason(QuitReason.SIGTERM, "Oh no, not again");
```
?

**Comment by mbax** [comment]
This was added for 3.0.0
