### ISSUE TITLE
Command convenience methods for all commands

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#118]
In #116 the idea of adding methods like newOperCommand to Client was brought up.

I feel the methods already provided for convenience on Channel are useful due to the potentially frequent usage. Operator commands, particularly OPER, are much more special case. Should KICL provided a new*Command in the relevant class for all commands?

**Comment by Zarthus** [comment]
My personal opinion: no.

Only commands that will be used should be added with convenience, the user should refer to the docs (you could provide a list of all commands) if they want to utilize KICL for it's fullest.

**Comment by kashike** [comment]
I say yes, only for consistency.

**Comment by mbax** [comment]
client.newCommand().away().message("Doot doot").execute().

```java
public interface Client {
    // other stuff already here obviously
    class Commands {
        // constructor, set variable client
        public AwayCommand away() {
            return new AwayCommand(this.client);
        }

        public KickCommand kick(String channel) {
            return new KickCommand(this.client, channel);
        }
    }
}

**Comment by mbax** [comment]
Moving to 2.0 for breaking idea of migrating existing commands in `Channel` to such a thing too.

**Comment by mbax** [comment]
Something like that, yes. Thoughts?

**Comment by Zarthus** [comment]
that list would probably be ending up rather long, I see no problem with it but I'd definitely separate commands from client in a new file.

**Comment by mbax** [comment]
How many commands are there, such that it'd end up long?

**Comment by mbax** [comment]
I'm migrating this out of 2.0.0 because I still don't feel this is an appropriate solution.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/23b484e9df6fa29bce35611ad1cba770407e2dbe
