### ISSUE TITLE
KSME on services Global

### ISSUE THREAD

**Issue by kashike** [KittehOrg/KittehIRCClientLib#123]
`org.kitteh.irc.client.library.exception.KittehServerMessageException: Error processing message: NOTICE message to improper target. Message: @time=2016-07-04T18:11:18.114Z :Global!service@rizon.net NOTICE $$irc.sxci.net :[Dwarf] Rizon staff would like to wish all our American chatters a happy 4th of July. Thank you for flying with Rizon and please don't light any fireworks in the cabin`

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/f7ff3723df8e4398083c258d346e81a85d387e46
