### ISSUE TITLE
Opt-in for echo-message and invite-notify

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#124]
echo-message runs the risk of being a nuisance for many folks. 
invite-notify could cause confusion for tracking, so why not

Any other capabilities to change from opt-out to opt-in?

**Comment by Zarthus** [comment]
These are all "maybes" depending on how they are implemented in KICL: 

SASL, batch, invite-notify (might be worth splitting up into ON SELF INVITE and ON INVITE events)

**Comment by mbax** [comment]
SASL is only done if added to authentication separately, so that's technically opt-in already.
batch is not yet implemented, and will totally be opt-in because oh god that would be messy
invite-notify makes sense, thanks!

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/29fbe8718c4ad90ac456f2fcdd07ec112c2ab53e
