### ISSUE TITLE
Send passwords with spaces with a colon in front

### ISSUE THREAD

**Issue by kenzierocks** [KittehOrg/KittehIRCClientLib#129]
Passwords that have a space should be prefixed with a colon so they are interpreted properly.

RFC reference: https://tools.ietf.org/html/rfc2812#section-2.3.1 (see `params`)

See also: https://github.com/hexchat/hexchat/issues/1550, https://github.com/znc/znc/issues/1188

**Comment by kashike** [comment]
Or just prefix all server passwords instead of special casing spaces?

**Comment by mbax** [comment]
Going off those issues, I find various references to situations where adding the colon ends in tears, so I'm adding it only when a space is present. 
https://github.com/KittehOrg/KittehIRCClientLib/commit/20d1918826c56e640f9d7f7716bdab6e08cb15c7
