### ISSUE TITLE
STS support

### ISSUE THREAD

**Issue by lol768** [KittehOrg/KittehIRCClientLib#139]
**What is it?**

It's similar to HSTS (HTTP Strict Transport Security) on the web, and it can be used by a server to tell the client "Hey, you! Don't connect to me over an insecure connection!".

**Why do we need it?**

The internet is a scary place now. We can't afford to do things in plaintext anymore, and IRC is no exception. There's been great success with HSTS on the web (although it's not as widespread yet as I would've hoped) and IRC should follow suit.

Servers  and clients that support this new capability will connect in a secure manner, **even if** the user misconfigures the client to connect over a plaintext port. It will also allow server operators/admins to seamlessly upgrade users to a secure connection if they haven't yet rolled out TLS.

**How's it related to the `tls` CAP?**

It's not, really. The STS spec says:

> In practice, switching protocols in the middle of the stream has proven to be complicated enough that only a small number of clients bothered implementing STARTTLS.

The reality for KICL is that it wasn't implemented because STARTTLS is actually a really, **really** awful idea easily defeated by an active MitM - not because the concept was "too complicated".

The `sts` system effectively replaces the `tls` capability and is actually a sane idea.

**Okay, how's it work?**

![](https://lol768.com/i/sts_paths.svg)

**Comment by mbax** [comment]
[http://www.oracle.com/technetwork/java/javase/8u101-relnotes-3021761.html](Java 8 update 101) and above supports [Let's Encrypt](https://letsencrypt.org/) by default as it now trusts IdenTrust. Are LetsEncrypt certs valid for IRC servers to use?

**Comment by lol768** [comment]
Would like to bag this for hacktoberfest, @mbax can you assign?

**Comment by lol768** [comment]
So! It looks like the folks over at Charybdis aren't going to implement this and have other, non-standard extensions planned which, to be honest, really miss the point (`tlswarning` doesn't do anything to enforce connections to the TLS service and it relies on users understanding and heeding the warnings, `chm_insecure` is a nice idea but won't automatically upgrade users to TLS connections and again relies on users understanding what's going on). They're useful tools for transitioning to TLS but don't replace STS at all. STS will help give us a better standard of security, since like with the HTTP equivalent (HSTS), invalid certificates cannot have on-connect exceptions created and the spec dictates the client properly validates certificates according to the trust store (or else refuses to connect).

I went to ask in their channel on freenode for more details but it's `+m` so I gave up. God knows why the channel is still mentioned on their site.

**Relevant:**

* http://charybdis.io/2016/01/30/charybdis-and-ircv3-3-sts.html
* https://github.com/ircv3/ircv3-specifications/issues/207

Not particularly impressed by the comments from kaniini on that spec issue to be honest, but the issues here on the KICL project are for technical details, not personal opinions on other software and I'm not going to expand on my thoughts.

I think the way forward for testing this is to either:

* Fork Charybdis/some other IRCd without STS support
* Add STS support that follows the spec without worrying too much about code quality and use this to test the Java client

Or:

* Find a better IRCd that supports STS natively
* Use it for testing purposes

Or:

* Test with a ZNC module again (since I'm familiar with the codebase a little more than a random IRCd)

Since the spec is still a draft, there's no compatibility table available yet so it might be challenging to find server software supporting this.

**Comment by lol768** [comment]
Steps on IRCd side:

* [ ] Fork charybdis on GitHub
* [ ] Get it to compile locally
* [ ] Configure test IRCd
* [ ] Generate self-signed SSL certificates for local test IRCd
* [ ] Get **valid, CA signed** certificate for local test IRCd (via Let's Encrypt)
  * Point DNS at valid external host, get certificate, point it back at localhost
* [ ] Familiarise self with charybdis codebase
* [ ] Add hardcoded STS support
* [ ] Recompile, confirm working via wireshark

**Comment by lol768** [comment]
IRCd support completed: https://github.com/lol768/charybdis/commit/a5f43d42ed1d8bc0b64955a5895558563c8ea970

**When connecting over plaintext port:**

```
<< CAP LS 302
>> :sts.adamwilliams.host CAP adam LS :account-notify account-tag away-notify cap-notify chghost echo-message extended-join invite-notify multi-prefix server-time sts=port=6697 tls userhost-in-names
```

**When connecting over secure port:**

```
<< CAP LS 302
>> :sts.adamwilliams.host CAP Testing LS :account-notify account-tag away-notify cap-notify chghost echo-message extended-join invite-notify multi-prefix server-time sts=duration=300 tls userhost-in-names 
```

-----

Now that that's out of the way the client work can begin \o/

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/3d097ecaa23127b662b66ca32463405b14f677f7
