### ISSUE TITLE
Proper distinguishment for "username" and "accountname" in KICLs authentication docs and protocols.

### ISSUE THREAD

**Issue by Zarthus** [KittehOrg/KittehIRCClientLib#145]
KICL is inconsistent with the distinguishment of Usernames and Accounts.

The current version of KICL calls authentication's name "username"s, which kind of work (especially with many versions of NickServ out there), but may be confused with usernames from irc (also referred to as idents).

Overall, I feel it would be better to be consistent overall and name them account names.

A few cases for both situations:
## Referred to as Username

https://github.com/KittehOrg/KittehIRCClientLib/blob/f5350fe2ef18ec4d61746e831ade81583fc4ba52/src/main/java/org/kitteh/irc/client/library/feature/auth/element/Username.java

https://github.com/KittehOrg/KittehIRCClientLib/blob/master/docs/advanced/alt_auth.md#nickserv

`PRIVMSG NickServ :IDENTIFY username password` - My username can be ~zarthus, my account name is Zarthus. Generally people will get the idea, though.

https://github.com/KittehOrg/KittehIRCClientLib/blob/f5350fe2ef18ec4d61746e831ade81583fc4ba52/src/main/java/org/kitteh/irc/client/library/feature/auth/SaslPlain.java#L49

getUsername makes it sound like we're getting the username/ident, not account name.

https://github.com/KittehOrg/KittehIRCClientLib/blob/40e92f6822fc90744438a503ae2d7cff09a103b1/src/main/java/org/kitteh/irc/client/library/Client.java#L278-L286
## Referred to as Account

https://github.com/KittehOrg/KittehIRCClientLib/blob/f5350fe2ef18ec4d61746e831ade81583fc4ba52/src/main/java/org/kitteh/irc/client/library/feature/auth/AbstractSaslProtocol.java#L107

https://github.com/KittehOrg/KittehIRCClientLib/blob/1be4b76904384597da8ba8b1bbd86417464e7b23/src/main/java/org/kitteh/irc/client/library/implementation/WhoisBuilder.java#L39

https://github.com/KittehOrg/KittehIRCClientLib/blob/f0af2f743ce383d7f740669c32a9d589bcc90f40/src/main/java/org/kitteh/irc/client/library/feature/CapabilityManager.java

https://github.com/KittehOrg/KittehIRCClientLib/blob/9632c9664975f35b7b20abfa4910d13de783d333/src/main/java/org/kitteh/irc/client/library/implementation/ActorProvider.java

---

There's no real "convention" between which is better, but considering `username` is already used for irc to notify the `nick!user@host part`, I think making it distinguishable would help, especially when it comes to coding completion for your IDE.

It's both up for debate, and if approved would likely result into backwards incompatible changes, hence the issue. It's usually clear with a bit of common sense, but I think use of Account Name would be more consistent and clear.

**Comment by mbax** [comment]
Authentication is in strong need of reworking, so this would go neatly with it. 

I think going toward account as the name for authentication is the right way, but I'd like more thoughts than mine and yours.

**Comment by lol768** [comment]
I agree on this, `account name` for NickServ account names and `username` for the element of the hostmask. This can be reinforced by JavaDocs/ a terminology guide on the docs website explaining which is being referred to so that new devs get the idea quickly.

**Comment by mbax** [comment]
This should handle it. https://github.com/KittehOrg/KittehIRCClientLib/commit/6dcfd267e1f08423d337b5049638e60375c000bd
