### ISSUE TITLE
Support a message burst for delays.

### ISSUE THREAD

**Issue by Zarthus** [KittehOrg/KittehIRCClientLib#147]
KICL currently supports a `messageDelay`, which is a flat delay between each message sent.

Ideally, it also supports a burst limit (that resets after either 10 seconds, or `burstDelay`) before the regular delay kicks in.

I think this also would deserve it's own page of documentation in docs if it were implemented.

**Comment by mbax** [comment]
This is something I'd like to see. Perhaps some sort of functional interface that returns how many millis before the next message is sent. That way, could still support someone providing just an integer, as that would then just be a steady message delay and KICL could wrap the int.

```java
@FunctionalInterface
public interface DelayDeterminer {
    /**
     * Gets the delay before the next message is sent
     *
     * @return delay
     */
    int getNextDelay();
}

public ClientBuilder messageDelay(DelayDeterminer determiner) {
    this.config.set(Config.MESSAGE_DELAY, determiner);
    return this;
}

public ClientBuilder messageDelay(int constantDelay) {
    return messageDelay(() -> constantDelay);
}
```

**Comment by mbax** [comment]
I've decided to go... a bit further than this.

https://github.com/KittehOrg/KittehIRCClientLib/commit/19a3d709b5eb4510a684eb6926b58edd7bb84b92

**Comment by Zarthus** [comment]
I dig it. Kittens to all whom were involved in thinking of and implementing
this idea!
