### ISSUE TITLE
Twitch support

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#162]
Helpful reference https://dev.twitch.tv/docs/v5/guides/irc/

* [ ] Twitch IRCv3 tags
* [ ] Support for delay limitations (20/100 per 30 seconds)
* [x] Longer messages https://github.com/KittehOrg/KittehIRCClientLib/commit/067137648c4bd718ac959fd65f3c27ce4c0ff188

**Comment by PhilippHeuer** [comment]
Can we also get a way to disable the missing server version exception and maybe a method in the builder to enable the twitch mode?
Right now im just filtering/ignoring all kitteh exceptions so that my monitoring doesn't get triggered.

**Comment by mbax** [comment]
I'm thinking about doing some sort of twitch compatibility builder item.

In the short term, this sort of strategy would work (split into separate if for readability):

```java
if(exception instanceof KittehServerMessageException) {
    KittehServerMessageException e = (KittehServerMessageException)exception;
    if (e.getMessage().contains("Server address and version missing.")) {
        return;
    }
}
```

or

```java
if(exception instanceof KittehServerMessageException) {
    KittehServerMessageException e = (KittehServerMessageException)exception;
    if (e.getServerMessages().size() == 1 && e.getServerMessages().get(0) instanceof NumericCommandServerMessage) {
        NumericCommandServerMessage n = (NumericCommandServerMessage) e.getServerMessages().get(0);
        if (n.getCommand() == 4) {
            return;
        }
    }
}
```

**Comment by mbax** [comment]
Moving over to PR - https://github.com/KittehOrg/KittehIRCClientLib/pull/187
