### ISSUE TITLE
Empty tag incorrectly parsed

### ISSUE THREAD

**Issue by Ribesg** [KittehOrg/KittehIRCClientLib#166]
Log of the problem: https://gist.github.com/Ribesg/1bdb68dcfffd0b798cbaed92790c0c17

Basically a tag with an empty value such as `badges=` should be parsed as a tag with name `badges`, and not `badges=`.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/03e1277a42ea18e19c2a75af86565ab70d58b506
