### ISSUE TITLE
Naming of removeChannel

### ISSUE THREAD

**Issue by lol768** [KittehOrg/KittehIRCClientLib#167]
* `removeChannel()` on `Client` does not trigger a `RequestedChannelLeaveEvent`
* `RequestedChannelLeaveEvent` only triggered for `part()` on `Channel`
* Inconsistency with `addChannel()` on `Client`

https://korobi.io/network/esper/channel/kitteh.org/logs/2016/12/10/#L119

**Comment by Ribesg** [comment]
`addChannel` also takes a vararg, `removeChannel` does not.

**Comment by Ribesg** [comment]
I have some problem with how `addChannel` works.

As far as I understand the code, `removeChannel` does nothing for unknown channels. It enqueues a message for "tracked channels", I'm not sure if those tracked channels are only channels the client is in, i.e. I'm not sure it only enqueues PART messages if needed.

My problems with `addChannel` are that:

1) It silently (!) does nothing if you pass an invalid channel name to it. It should throw an exception violently instead.*
2) If the passed channel name is valid based on server rules, it immediately enqueues a JOIN message. Why? We may be already in this channel, it's a waste of messages, and with 2 seconds between each message... :P

*Also occurs in other parts of the code, somewhere deep into `removeChannel` too iirc.

**Comment by Zarthus** [comment]
@Ribesg: What would an invalid channel name include?  I know KICL currently does not support `,` notation, but channel names can be very broad that it's near-impossible to validate it and what is valid depends per server and IRCd. The only 'truly' illegal character I know of is a space, but even then there are addons (like bitlbee) that mimic behaviour like IRC that might totally still accept spaces in channel names.

KICL could listen to some\* popular numerics, these are defined in RFC [[source](http://defs.ircdocs.horse/defs/numerics.html)]:


```
403	ERR_NOSUCHCHANNEL	  RFC1459	<client> <channel> :<reason>	Used to indicate the given channel name is invalid, or does not exist
404	ERR_CANNOTSENDTOCHAN  RFC1459	<client> <channel> :<reason>	Sent to a user who does not have the rights to send a message to a channel
405	ERR_TOOMANYCHANNELS   RFC1459   <client> <channel> :<reason>	Sent to a user when they have joined the maximum number of allowed channels and they tried to join another channel
471	ERR_CHANNELISFULL	RFC1459	<client> <channel> :<reason>	Returned when attempting to join a channel which is set +l and is already full
472	ERR_UNKNOWNMODE	RFC1459	<client> <char> :<reason>	Returned when a given mode is unknown
473	ERR_INVITEONLYCHAN	RFC1459	<client> <channel> :<reason>	Returned when attempting to join a channel which is invite only without an invitation
474	ERR_BANNEDFROMCHAN	RFC1459	<client> <channel> :<reason>	Returned when attempting to join a channel a user is banned from
475	ERR_BADCHANNELKEY	RFC1459	<client> <channel> :<reason>	Returned when attempting to join a key-locked channel either without a key or with the wrong key
476	ERR_BADCHANMASK	RFC2812	<client> <channel> :<reason>	The given channel mask was invalid
```

And these are made up without collisions:
```
448	ERR_FORBIDDENCHANNEL	Unreal	<channel> :Channel is forbidden: <reason>	Returned when this channel name has been explicitly blocked and is not allowed to be used.
495	ERR_DELAYREJOIN	InspIRCd	<channel> :You cannot rejoin this channel yet after being kicked (+J)	This numeric is marked as "we should use 'resource temporarily unavailable' from ircnet/ratbox or whatever"
488	ERR_NOSSL	Bahamut	<client> <channel> :SSL Only channel (+S), You must connect using SSL to join this channel.
490	ERR_ALLMUSTSSL	Unreal, apparently	<client> <channel> :all members of the channel must be connected via SSL
485	ERR_CHANBANREASON	Hybrid	<client> <channel> :Cannot join channel (<reason>)	
```

Probably by no means an exhaustive list. I know of 495 being not uncommon and more and more ircds are looking to support ssl-only channels, but that's it.

**Comment by Ribesg** [comment]
@Zarthus I think you REALLY misunderstood what I meant.

https://github.com/KittehOrg/KittehIRCClientLib/blob/master/src/main/java/org/kitteh/irc/client/library/implementation/IRCClient.java#L129

I just mean that this continue should be a throw. There is the same kind of code elsewhere.

**Comment by lol768** [comment]
👍 on not silently ignoring invalid channels. Should be defensive like the rest of the codebase is with the Sanity checks etc and `throw` ASAP.

JavaDoc should be updated though.

**Comment by mbax** [comment]
Reject invalid names in addChannel methods https://github.com/KittehOrg/KittehIRCClientLib/commit/46de54bad31aba4dde19ec80458882887287a990

**Comment by mbax** [comment]
Remove unnecessary channel part checks https://github.com/KittehOrg/KittehIRCClientLib/commit/f5a8a35b6e67af8f4c34920ed491ba5f81292456

**Comment by mbax** [comment]
Meant to close after this one.

Requested -> Unexpected for unexpected channel leave

https://github.com/KittehOrg/KittehIRCClientLib/commit/f32b6d572c2e08e04452b06029e611e3b35a273e
