### ISSUE TITLE
Client#getNick() returns expected nick, not current nick

### ISSUE THREAD

**Issue by jkcclemens** [KittehOrg/KittehIRCClientLib#17]
For example, a bot was joining as TheHumanity, but that nick was already taken, so it joined as TheHumanity`. However, the getNick method returned TheHumanity.

**Comment by turt2live** [comment]
> butt

**Comment by jkcclemens** [comment]
You know what was on my mind. Fixed.

**Comment by turt2live** [comment]
Also can confirm this on a different project. turt2bot has a similar issue where it assumes it was able to get the nick defined.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/4cd849f7ddc25aff65599db7dfed3e8089716ad7
