### ISSUE TITLE
I accidentally broke all insecure connections (when STS is off)

### ISSUE THREAD

**Issue by lol768** [KittehOrg/KittehIRCClientLib#173]
https://github.com/KittehOrg/KittehIRCClientLib/blob/master/src/main/java/org/kitteh/irc/client/library/implementation/IRCClient.java#L200

Part of me will be disappointed when this is fixed. Also I shouldn't have been able to break it this bad.. maybe we can do some integration testing or something

/ cc @kenzierocks

**Comment by Zarthus** [comment]
s/broke/fixed/g

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/8fc8af26850ae59068e859f622891da81c5e6a3c
