### ISSUE TITLE
Oops

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#175]
https://github.com/KittehOrg/KittehIRCClientLib/commit/43404758a664cae0640ec92861553bc97c4df96c#commitcomment-20369645

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/626b332c9e3a5ee04aa4589fd7a59638a0993d55

Thanks @bendem

**Comment by bendem** [comment]
At your service
