### ISSUE TITLE
ChannelModeEvent not firing on channel join

### ISSUE THREAD

**Issue by kashike** [KittehOrg/KittehIRCClientLib#177]
`ChannelModeEvent` does not fire during channel join, when modes are received.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/blob/master/src/main/java/org/kitteh/irc/client/library/implementation/EventListener.java#L395-L415

I feel like there was a reason for this happening. Any ideas?

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/361f3f04a463bff5ff15fc6183a11abbda8f7978

Proposed solution
