### ISSUE TITLE
KICL constantly connects to the same server

### ISSUE THREAD

**Issue by Zarthus** [KittehOrg/KittehIRCClientLib#183]
When connecting to a dns pool (such as `irc.esper.net`), KICL should pick a random server rather than cache only a single one and always pick that one (even if for a brief time).

Caching them for a while isn't bad, just don't always pick the same server.

It was indicated this might not be KICL itself, but I believe the code should work around java "features" if this is the case.

**Comment by bendem** [comment]
```
09:35:07 <+bendem> Zarthus, -Dnetworkaddress.cache.ttl=0 will fix dns caching
09:35:09 <+bendem> see https://docs.oracle.com/javase/8/docs/api/index.html?java/net/InetAddress.html
```

**Comment by mbax** [comment]
@bendem  But then you also have no cache, right? So if the DNS hiccups at the same moment your connection hiccups, you're not reconnecting even if it would have been possible with DNS caching.

**Comment by mbax** [comment]
http://www.dnsjava.org/ maybe?

**Comment by mbax** [comment]
With this commit - https://github.com/KittehOrg/KittehIRCClientLib/commit/cab2851297a8b357202b306de5b7b8fdb1e583f5 - KICL will now at least cycle the resolved IPs.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/pull/239

Part one complete, which also resolves this specific issue. #237 remains open as a bigger-picture issue.
