### ISSUE TITLE
Is it possible to use KICL in a sandboxed environment?

### ISSUE THREAD

**Issue by SoniEx2** [KittehOrg/KittehIRCClientLib#186]
Say I have a sandboxed environment with sockets. Can I just implement an interface or something to make KICL use the sandbox sockets?

**Comment by lol768** [comment]
> sandboxed environment with sockets

Perhaps you could elaborate, in detail, on this environment? As I'm sure you're aware KICL is designed to connect using TCP (with TLS on top recommended), to a provided host/port pair.

Is there anything stopping you from listening locally, accepting TCP connections and then bridging data back and forth to any "sandbox sockets" you maintain if you're really not happy with how KICL normally handles connections?

In any case, I don't think this is something that is abstracted away in the current codebase - so no, there isn't a simple interface to implement. 

----------

This seems like an uncommon usecase and at present it's not particularly well justified. It would be useful if you could explain the motivation in detail - without that, the benefit of implementing such functionality is dubious.

**Comment by SoniEx2** [comment]
See MovingBlocks/Terasology#2901 and MovingBlocks/Terasology#2618

The use-case would be a bridge bot.

**Comment by lol768** [comment]
Is there a reason you're unable to use a Java security manager and appropriate policy that grants socket permissions (e.g. `permission java.net.SocketPermission "some.host.com:6697", "connect";`?

**Comment by SoniEx2** [comment]
1. Can I filter that based on module?
2. How can I be sure a library (such as awt) doesn't expose arbitrary sockets somehow?

**Comment by lol768** [comment]
> Can I filter that based on module?

Can you extend `java.lang.SecurityManager`, override the necessary socket related methods and make use of `getClassContext` to check your module?

> How can I be sure a library (such as awt) doesn't expose arbitrary sockets somehow?

I mean, if it uses `java.net.Socket` then there's [going to be a check](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/net/Socket.java#528) against the security manager. I'm not sure I understand the concern here.

**Comment by SoniEx2** [comment]
1. Does this lib require netty? If so, I'd still need a way to use a custom socket thingy, since the sandbox doesn't handle having a package both in the engine and in a module at the same time.
2. I'm not sure if there are any technical reasons for not using SecurityManager, other than that the rest of the engine doesn't use it.

**Comment by lol768** [comment]
Yeah, KICL requires Netty.

Regarding `SecurityManager`, I'd definitely recommend considering it. I don't fully understand the usecase yet - but couldn't I bypass your implementation by using reflection to access `SocketAccessImpl` (specifically the `allowedHosts` field)? Using a SecurityManager would allow you to disallow this sort of thing, along with stopping users replacing the SecurityManager etc.

**Comment by SoniEx2** [comment]
I don't think you can - this is how the rest of the engine works, altho I'm not sure how well it has been tested.

**Comment by bendem** [comment]
The SecurityManager is the solution, everything else can be bypassed with reflection. You're adding problems by adding abstractions, not solving them.

You might want to read [this](https://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html) and [this](https://tersesystems.com/2015/12/29/sandbox-experiment/)

**Comment by mbax** [comment]
I feel this has been adequately answered with "Yes you can do all sorts of things with existing tools!"

**Comment by SoniEx2** [comment]
Reflection doesn't work, and even if it did it can't cross classloader boundaries.

@mbax Can I replace KICL's socket/connection backend? e.g. replace netty with plain java, or a sandbox, or a proxy lib. I feel like that question hasn't been answered yet.

**Comment by mbax** [comment]
KICL is built to do netty-stuffs. I haven't yet provided API for swapping out networking, though it's on the big todo list.

**Comment by bendem** [comment]
> @bendem Reflection doesn't work, and even if it did it can't cross classloader boundaries.

I think you might need to revise your knowledge of reflection. Classloading is irrelevant to this problem.

```
➜ jar tf jar.jar
META-INF/
META-INF/MANIFEST.MF
a/
a/a.class
a/a.java
➜ cat a/a.java
package a;

public class a {
    private int i = 2;
}
➜ java.py -i java.net.\* 'Class<?> c = new URLClassLoader(new URL[] {
        Paths.get("jar.jar").toUri().toURL()
    }).loadClass("a.a");
    Field f = c.getDeclaredField("i");
    f.setAccessible(true);
    f.get(c.newInstance())'
>> (Integer) 2
```
