### ISSUE TITLE
Provide a way to provide a custom EventManager

### ISSUE THREAD

**Issue by kashike** [KittehOrg/KittehIRCClientLib#189]
Provide a way (via `Client.Builder`) to provide a custom `EventManager`, rather than forcing use of `org.kitteh.irc.client.library.implementation.ManagerEvent`.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/ecd68dabf303124b9814581c341ef028ef42a3ad

For 3.2.0
