### ISSUE TITLE
DefaultMessageMap#getDefault(type, defaultValue) shouldn't return an optional

### ISSUE THREAD

**Issue by bendem** [KittehOrg/KittehIRCClientLib#195]
While it makes sense for `DefaultMessageMap#getDefault(type)` to return an `Optional`, I think `DefaultMessageMap#getDefault(type, defaultValue)` should definitely reject null default values and return a `String`.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/ce75e4b82af31fb3462fb27abaf18ea3adab55eb

**Comment by mbax** [comment]
Per discussion on IRC, closing without resolution.
