### ISSUE TITLE
Improve toString output

### ISSUE THREAD

**Issue by kashike** [KittehOrg/KittehIRCClientLib#197]
- [ ] `ServerInfo`: `IRCServerInfo (client=IRCClient (name=somename, server=localhost/127.0.0.1:1234))`
 - doesn't include:
   - [ ] address
   - [ ] channel modes
   - [ ] channel prefixes
   - [ ] channel user modes
   - [ ] isupport parameters
   -  ~~motd~~
   - [ ] version
   - [ ] user modes

**Comment by mbax** [comment]
Into (soon) 3.3.0 it goes! 

https://github.com/KittehOrg/KittehIRCClientLib/commit/c66ee5e77ee2bcc2256c0156e56f98db70da2189

**Comment by kashike** [comment]
Almost. The getters need to be used! :3

**Comment by mbax** [comment]
\*cough\*

https://github.com/KittehOrg/KittehIRCClientLib/commit/1693b8795c8c8caba00edff426d2cf64676b1def

**Comment by kashike** [comment]
Oops! https://github.com/KittehOrg/KittehIRCClientLib/commit/1693b8795c8c8caba00edff426d2cf64676b1def#diff-52bd9e475c8a85ac41ba3643ff2e14cfL207

**Comment by mbax** [comment]
\*sob\*

https://github.com/KittehOrg/KittehIRCClientLib/commit/758a8c79ca686b890d21a6d7e99fe08468e5aeaf
