### ISSUE TITLE
Question: Xamarin C# compatibility?

### ISSUE THREAD

**Issue by TheXenocide** [KittehOrg/KittehIRCClientLib#205]
Hello, just wondering if you guys happen to know if this library would be compatible with a Portable Class Library or what it would take to modify the code to get that working?

**Comment by TheXenocide** [comment]
My bad, this is a Java project, isn't it? Apologies, doing things a little out of order this morning 😜

**Comment by kashike** [comment]
Yes, this is a Java project.

**Comment by TheXenocide** [comment]
Thanks kindly for your patience

**Comment by Zarthus** [comment]
Good morning.

**Comment by lol768** [comment]
FWIW I'd love a C# (.NET Core compatible) port of this 👅

**Comment by TheXenocide** [comment]
Seems I have a million side projects l;ately, but I'd be happen to provide one if I find the Time 💝

**Comment by mbax** [comment]
Have my favorite issue label.
