### ISSUE TITLE
Clearer exception information

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#214]
Not all users will read the documentation online. Some possibilities, which could be done alone or together:

1. Startup notice on default exception handler.
```Starting Kitteh IRC Client Library. Please remember most exceptions printed here aren't actually stopping the client. This default exception handler prints them all out anyway. Report exceptions to https://kitteh.org/report to assist development.```
(and the /report url goes to here)

2. Per-exception notice on default exception handler.
```An exception occurred! This exception may introduce trouble in your client but, other than a connection problem, KICL will continue to function!```

3. Make nag exception very clear.
```This is not a bug in KICL. This is a reminder to the developer of the software utilizing KICL to fix $thing```

**Comment by bendem** [comment]
```
18:15:40 <@Zarthus> I like (1), (3) with a slight bit of rephrasing
18:16:19 <+bendem> I'd rather go with 3
18:16:37 <@Zarthus> the problem with (1) is that it can't be turned off
18:16:44 <+bendem> the error should only happen on connect, so he'll see it if it happens
18:16:56 <+bendem> and it won't confuse him if it doesn't, like 1 and 2 would
18:17:13 <+bendem> and well, if you know, 1 and 2 are going to be annoying
18:17:48 <@Zarthus> maybe (3) and a specific document on NagExceptions in docs/
18:18:18 <+bendem> yup, that'd be the optimum solution imo
```

**Comment by mbax** [comment]
@Zarthus Option one would just be for the default handler, and could be turned off by changing the exception handler.

**Comment by Zarthus** [comment]
I don't like having to override a default class just because it throws a message i'd rather only see once, and once i've read it never show me it again.

Maybe there's a maven post-install message thing that might make more sense to implement it in?

**Comment by mbax** [comment]
Per IRC, no maven-based thing that would be read. Goal is for users to see info.

**Comment by mbax** [comment]
Starting with just this, will expand further if necessary.
https://github.com/KittehOrg/KittehIRCClientLib/commit/e27eb9bf72ec8bc27a321947a4c90ac4a649538f
