### ISSUE TITLE
Add method to Client to determine if on Twitch

### ISSUE THREAD

**Issue by kashike** [KittehOrg/KittehIRCClientLib#215]
[This](https://github.com/KittehOrg/KittehIRCClientLib/blob/master/src/main/java/org/kitteh/irc/client/library/implementation/EventListener.java#L143) really should be done in a different way, such as:
- [ ] `Client#isTwitch()` - straight to the point
- [ ] `Client#isSupported(Client.Platform.TWITCH)` - allows additional "platforms" to be added and tested for, without adding a new method to `Client` for each one

**Comment by Zarthus** [comment]
I don't disagree that the line could use some improvements, but I don't think this should be part of any public API at all.
