### ISSUE TITLE
support android

### ISSUE THREAD

**Issue by LucasParsy** [KittehOrg/KittehIRCClientLib#217]
hello,

when building my android app with minSDK version 16, I get this error:

`Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing org/kitteh/irc/client/library/implementation/IRCClient.class`

`Error:com.android.dx.cf.code.SimException: default or static interface method used without --min-sdk-version >= 24`

when I set my minSDK to 24, I get this error:

`Error:java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex `

can the library be used on Android?

I use Gradle with Android studio 3.0.1.

**Comment by mbax** [comment]
According to the Android  [Java 8 features](https://developer.android.com/studio/write/java8-support.html#supported_features) page, there's a lot of stuff that's API 24 and up. 

* `java.util.stream` is used in a lot of places throughout the codebase.
* `java.util.function` sees a lot of use in the KICL API.

Seeing the SimException about default methods in the context of that documentation table is weird, but it also being minimum 24 doesn't really make things worse.


As for the dex merging exception, I'd be interested in seeing more of an error on that. Surely there's more to it than that one line? I've received more detailed bug reports in the past with Android use that made it past the build stage. I have not personally tested using the library on Android but would be happy to assist as possible.

**Comment by LucasParsy** [comment]
thank you very much for your fast response.
I switched to PircBot, a simpler and older IRC library, compatible with Android.

It is too late for me to reproduce the Dex merging issue, but from what I saw, the exception showed no direct mention to your library, this being maybe an internal Gradle error.

**Comment by mbax** [comment]
Thanks for the update. I'll close this for now.
