### ISSUE TITLE
Include an automatic module name in the manifest

### ISSUE THREAD

**Issue by kashike** [KittehOrg/KittehIRCClientLib#230]
http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

**Comment by mbax** [comment]
Not sure how poorly I read that article: Shouldn't I be waiting the until all my dependencies are modules?

**Comment by DemonWav** [comment]
Nope. Automatic module name eases the transition period, specifically for the case when all of your dependencies aren't using modules.

If all of your dependencies were using modules you could easily just use modules directly.

**Comment by mbax** [comment]
PR pulled! :)
