### ISSUE TITLE
KICL is stripping off a leading colon in a message with multiple colons

### ISSUE THREAD

**Issue by zachbr** [KittehOrg/KittehIRCClientLib#234]
When listening to channel messages w/ KICL, in certain circumstances it strips off the leading colon character. I have no thoroughly tested this issue to see if it's specific to just colons, or some other subset of characters.

The following are the limited test cases I've tried, they should always match, but they don't.
The left is what is being sent in IRC and the right is what is being received in the KICL event.
`:something:`             -> `:something:`
`:something::something:`  -> `:something::something:`
`:something: :`           -> `something: :`
`:something : :`          -> `something : :`
`:something: :something:` -> `something: :something:`

In the following screenshot, I sent `:taco: :taco:`, but I get `taco: :taco:` from the KICL event, as you can see in the debugger.
![debugger](https://i.imgur.com/uKboNgb.png)

**Comment by mbax** [comment]
Wow, that's quite the bug! Thank you to @kashike for handling this while I slept!

**Comment by mbax** [comment]
KICL 4.0.3 headed to maven central shortly.
