### ISSUE TITLE
addModeChange(true, 'b', this.user)

### ISSUE THREAD

**Issue by kashike** [KittehOrg/KittehIRCClientLib#26]
Caused by: java.lang.IllegalArgumentException: Provided mode `b' requires a mask parameter.

**Comment by mbax** [comment]
Yup, you can send whatever you want at the server.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/7fd3a22cc0afd552815cf6ce88355d047e1fc83d
