### ISSUE TITLE
ISUPPORT MAXLIST

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#265]
To quote [modern.ircdocs.horse](https://modern.ircdocs.horse/#maxlist-parameter):

```
MAXLIST=beI:25           ; indicates that a client may set up to a total of 25 of a
                         combination of "b", "e", and "I" modes.

MAXLIST=b:60,e:60,I:60   ; indicates that a client may set up to 60 "b" modes,
                         "e" modes, and 60 "I" modes.

MAXLIST=beI:100,q:50     ; indicates that a client may set up to a total of 100 of
                         a combination of "b", "e", and "I" modes, and that they
                         may set up to 50 "q" modes.
```

Options:
* `Set<Pair<Set<Character>,Integer>>` 
* `Map<Set<Character>,Integer>>`

Thoughts?

**Comment by mbax** [comment]
Went a slightly different route https://github.com/KittehOrg/KittehIRCClientLib/commit/639c773530ea3548891e382474bf2560316a0387

**Comment by mapsler** [comment]
![mapsler health news app cross pay comand](https://user-images.githubusercontent.com/89662644/134489145-8ceb35bb-312a-4c21-8ff1-b6bad193afd5.png)
