### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [KittehOrg/KittehIRCClientLib#274]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/org/kitteh/irc/client/library/feature/auth/SaslEcdsaNist256PChallenge.java: Line number => 283: API name => Signature:First parameter (with value "NONEwithECDSA") should be any of {NONEwithDSA, SHA1withDSA, SHA224withDSA, SHA256withDSA, SHA256withRSA, SHA256withECDSA}<BR> File name => src/main/java/org/kitteh/irc/client/library/feature/auth/SaslEcdsaNist256PChallenge.java: Line number => 260: API name => KeyPairGenerator:First parameter (with value "EC") should be any of {RSA, DSA, Diffie-Hellman}<BR> File name => src/main/java/org/kitteh/irc/client/library/feature/auth/SaslEcdsaNist256PChallenge.java: Line number => 246: API name => Signature:First parameter (with value "NONEwithECDSA") should be any of {NONEwithDSA, SHA1withDSA, SHA224withDSA, SHA256withDSA, SHA256withRSA, SHA256withECDSA}<BR> File name => src/main/java/org/kitteh/irc/client/library/feature/auth/SaslEcdsaNist256PChallenge.java: Line number => 263: API name => KeyPairGenerator:<BR> File name => src/main/java/org/kitteh/irc/client/library/feature/auth/SaslEcdsaNist256PChallenge.java: Line number => 249: API name => Signature:<BR> File name => src/main/java/org/kitteh/irc/client/library/feature/auth/SaslEcdsaNist256PChallenge.java: Line number => 287: API name => Signature:<BR>

**Comment by lol768** [comment]
@mhp0rtal Please stop it. Your automated tool is too dumb/old to understand that there is such a thing as an ECDSA signature, and you're making yourself look foolish as a result. You're not helping to improve security here, you're just wasting people's time. There are no security issues here.

**Comment by lol768** [comment]
@mbax can you lock/limit to collaborators and close this, please?

**Comment by mbax** [comment]
Closed because @mhp0rtal is a bot and didn't even check for false positives, which these are.
