### ISSUE TITLE
Warn user when building if port == 6667 and secure is set to true, tell user to use port 6697

### ISSUE THREAD

**Issue by lol768** [KittehOrg/KittehIRCClientLib#276]
**What is the feature or improvement?**
See title.

Suggestion from @bendem

**Comment by bendem** [comment]
Or as suggested on IRC, provide an API call that includes both the port and the use of TLS: `securePort(int)` / `insecurePort(int)` / `plaintextPort(int)` / `portAndSecure(int, bool)`

**Comment by mbax** [comment]
Via IRC:
`<+kashike> maybe just port(int, SecurityType)? enum SecurityType { /** TLS. */ SECURE, /** No TLS. */ INSECURE; }`

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/3e91677b57ce088a7062753bdc171dadfd93d73c

in `next`
