### ISSUE TITLE
Document CTCP version and finger customization

### ISSUE THREAD

**Issue by jottinger** [KittehOrg/KittehIRCClientLib#280]
RIght now, CTCP VERSION responds with a hard-coded "I am Kitteh!" and FINGER returns "om nom nom tasty finger" as shown in https://github.com/KittehOrg/KittehIRCClientLib/blob/master/src/main/java/org/kitteh/irc/client/library/defaults/listener/DefaultPrivmsgListener.java#L76 and https://github.com/KittehOrg/KittehIRCClientLib/blob/master/src/main/java/org/kitteh/irc/client/library/defaults/listener/DefaultPrivmsgListener.java#L82 . These are humorous, but it's not clear how to override these results.

**Comment by mbax** [comment]
Oh cool you can assign me automatically. 

In the short term (before documentation): Just listen to `PrivateCtcpQueryEvent` and use the getReply/setReply methods.

**Comment by jottinger** [comment]
That means still manually parsing out the action, as I understand it?

**Comment by mbax** [comment]
Every CTCP query a user sends to the client causes that event to fire. For the ones KICL adds the replies to, `getReply()` would return those responses in the event, but it can just be replaced with `null`. If you want no CTCP queries responded to at all, you could just:
```java
@Handler
public void nothx(PrivateCtcpQueryEvent event) {
    event.setReply(null);
    // Or then do your own replies based on what's sent here.
}
```

**Comment by jottinger** [comment]
Thank you. The code I'm using is kotlin, and delegates to an injected reference, referred to here for posterity's sake:

    @Handler
    fun onPrivateCTCPEvent(event:PrivateCtcpQueryEvent) {
        when(val ctcpMessage = event.message.split("//s").firstOrNull()) {
            "VERSION" -> event.setReply("$ctcpMessage ${bot.versionResponse}")
            "FINGER" -> event.setReply("$ctcpMessage ${bot.fingerResponse}")
            else -> Unit
        }
    }

**Comment by mbax** [comment]
Forgot to push this and comment here.

https://github.com/KittehOrg/KittehIRCClientLib/commit/6f8d9ba3090b3e6ff01d0315171dafe94a3fc663
