### ISSUE TITLE
KittehConnectionException : Connection refused: no further information: /127.0.0.1:6697

### ISSUE THREAD

**Issue by CoreException1312** [KittehOrg/KittehIRCClientLib#294]
Hey,
I get an exception:

`org.kitteh.irc.client.library.exception.KittehConnectionException: io.netty.channel.AbstractChannel $ AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:6697.
`

I use this code:
```
public static class Listener {
        @Handler
        public void onUserJoinChannel(ChannelJoinEvent event) {
            if (event.getClient().isUser(event.getUser())) {
                event.getChannel().sendMessage("Hello! CoreException is there!");
                return;
            }
            event.getChannel().sendMessage("Welcome, " + event.getUser().getNick() + "!");
        }
    }

    public static void main(String[] args) {
        Client client = Client.builder().nick("CoreBot").server().host("127.0.0.1").then().buildAndConnect();
        client.getEventManager().registerEventListener(new Listener());
        client.addChannel("#coreexception");
    }
```

The error also occurs with other IPs...

Full Exception: https://pastebin.com/UQ2gUNqa

Many thanks in advance! :)

**Comment by bendem** [comment]
Do you have an IRC server running locally? Because that's where your code tries to connect.

**Comment by CoreException1312** [comment]
> Do you have an IRC server running locally? Because that's where your code tries to connect.

Yikes, that's right, I didn't think of that. Thank you! I will set up an IRC server and then try again. Write then again whether it worked or not (:

**Comment by CoreException1312** [comment]
> Do you have an IRC server running locally? Because that's where your code tries to connect.
