### ISSUE TITLE
Still requiring the minSdkVersion for Android?

### ISSUE THREAD

**Issue by liuyuchih** [KittehOrg/KittehIRCClientLib#297]
**What is the feature or improvement?**
From the [android integration guide  ](https://kitteh-irc-client-library.readthedocs.io/en/latest/android/), it said we should set minSdkVersion >= 24.
But from my testing with minSdkVersion 19, I still could get the messages from the ChannelMessageEvent correctly.

Base on the [document](https://developer.android.com/studio/write/java8-support#library-desugaring), If you're building your app using Android Gradle plugin 4.0.0 or higher, the plugin extends support for using a number of Java 8 language APIs without requiring a minimum API level for your app.

So I guessed we don't need this restriction any more? If this is correct, please also update the document. Thanks.

**Comment by liuyuchih** [comment]
Hmm, I did another test on Android device 6.0, the app will crash on it, because KittehIRCClientLib has used [getAnnotationsByType](https://developer.android.com/reference/java/lang/reflect/AnnotatedElement#getAnnotationsByType(java.lang.Class%3CT%3E)) required api level 24+.

**Comment by mbax** [comment]
My favorite issues are one that resolve while I sleep and work! 

Thanks for doing the testing for this 😄

**Comment by liuyuchih** [comment]
Ha, you're welcome... XD
According to this [report](https://www.appbrain.com/stats/top-android-sdk-versions), there are still ~10% users on Android 5 & 6. 
It will be great if we could use this lib with minSdkVersion < 24 (Android 7).
But I guess it's not easy to remove the getAnnotationsByType or other dependency required on api level 24.
