### ISSUE TITLE
Don't send pong message from irc server

### ISSUE THREAD

**Issue by R3ALW1NNER** [KittehOrg/KittehIRCClientLib#305]
**Expected behavior**
We changed the ping frequency of the IRC server from the default 2 minutes to shorter.

I received a ping message from the client, but I didn't send a pong, so the connection is disconnected.

If you have received a ping message, you must send a pong.

**Actual behavior**

**Stacktrace**

**To Reproduce**

**Version information**
 - OS: Centos7
 - JVM: Temurin 11.0.13+8
 - KICL version: 7.4.0

**Additional context**
I couldn't find the part about ping pong in the document.

If there's a solution, please let me know.

**Comment by R3ALW1NNER** [comment]
sorry I closed it by mistake.

**Comment by bendem** [comment]
PING is handled as soon as the line is received before any other parsing or processing. If KICL is not responding to the server's PING, either it's not processing messages at all, or you are actually disconnected.

https://github.com/KittehOrg/KittehIRCClientLib/blob/f7317e61d7ebd48a4293c5b10c67d576a95943de/src/main/java/org/kitteh/irc/client/library/defaults/DefaultClient.java#L721-L727
