### ISSUE TITLE
Helper methods

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#33]
```
<@Zarthus> #getBans, #getUserlist, #isVoiced(User), #isOpped(User),
                 #isHalfop(User), #getOps, #getHalfOps, #getVoices, #ban(User),
                 #deop(User), #op(User), #kick(User, reason), #remove(User,
                 reason), #unban(mask), #voice(User), #devoice(User)
```

**Comment by mbax** [comment]
Proposing the following:

###Bans

* Acquire bans list upon join
    * Consider making it possible to disable in the `ChannelJoinEvent`
* Provide bans via `Channel#getBans()`
    * `ChannelBan` interface defining mask, who banned, time
* `BanCommand` command helper allowing +b and -b
    * `Channel#addBans()` shortcut to it

### Modes
I feel that this is already fairly well supported, now that there's methods to get modes by character.

**Comment by kashike** [comment]
`#kickban(User, String)`

**Comment by mbax** [comment]
Client#isUser(User) self-check

Helper methods for processing message tags.

**Comment by havokoc** [comment]
```java
#isProtected(User), #getProtected, #isOwner(User), #getOwner(),
#getTopic, #getInviteExemptions, #getBanExemptions, #getMutes
```

**Comment by jamietech** [comment]
`#ban(String)`

**Comment by mbax** [comment]
I'm closing this in favor of specific issues.
