### ISSUE TITLE
Improve builder method naming

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#37]
Current naming scheme for removal of set values is... confusing. Just the same name but no parameters? Need a better solution.

**Comment by kashike** [comment]
Either allow `null` to be passed, or include `remove` in the name.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/7bd599090c2a534a814d4e5969b7cbab055d5ef1
