### ISSUE TITLE
PKP API

### ISSUE THREAD

**Issue by lol768** [KittehOrg/KittehIRCClientLib#44]
KICL should support mapping hostnames to public keys, in SHA256 base64 encoded format. This should ideally match the format in RFC 7469: https://tools.ietf.org/html/rfc7469#section-2.4.

We want to avoid hashing certificates and using fingerprints of certificates. Instead, we hash SubjectPublicKeyInfo from inside the X509 cert. See https://www.imperialviolet.org/2011/05/04/pinning.html for reasoning, summarised below:

> In general, hashing certificates is the obvious solution, but the wrong one. The problem is that CA certificates are often reissued: there are multiple certificates with the same public key, subject name etc but different extensions or expiry dates. Browsers build certificates chains from a pool of certificates, bottom up, and an alternative version of a certificate might be substituted for the one that you expect.

> For example, StartSSL has two root certificates: one signed with SHA1 and the other with SHA256. If you wished to pin to StartSSL as your CA, which certificate hash would you use? You would have to use both, but how would you know about the other root if I hadn't just told you?

**Things that might be important to consider:**

* Might need to be careful with round-robins. ~~Need to use the 'latest' hostname to match with a public key pin.~~ Edit (07/02/16): No we don't and this is a stupid idea. We use the hostname provided verbatim by the developer regardless of whether that points elsewhere via a CNAME or whatever. This follows browser behaviour.
* Might want to consider different possible modes of operation:
  * For certificates which we have a matching pin for:
    * We can accept them regardless of validity
    * We can accept them if they're not expired and for the correct hostname, but are self-signed
    * Or only accept them if they're valid in addition to the pin (not expired, issues by a trusted CA etc)
  * For certificates which we *don't* have a matching pin for:
    * We can reject them all
    * We can accept them if they pass the aforementioned validity checks
    * We can accept them all regardless of whether they're valid (least secure)
* I don't think we need to consider SNI, want to check this though.

We could perhaps have two enums to configure this?

**Comment by lol768** [comment]
**API ideas:**

`ClientBuilder` extended to have new method:

`@Nonnull IPkpSettings publicKeyPinningSettings();` (or perhaps the shorter`@Nonnull IPkpSettings pinningSettings();`)

New interface, `IPkpSettings` (or whatever naming convention matches what you currently use):

* `void addPinForHostname(string hostname, string pin);`
* `void removePinForHostname(string hostname);`
* `bool isHostnamePinned(string hostname);`
* `IDictionary<string, string> getAllPins();` (hostname => pin dictionary)

Do we want to be able to have multiple possible public key pins per hostname? The above would need to change if that were the case.

-----

Also worth noting EsperNet's fingerprints are for entire certificates (they're also outdated but that's been brought up to get fixed). Users would need to be aware that they need to provide **public key** fingerprints and not certificate fingerprints.

**Comment by lol768** [comment]
Some discussion: https://korobi.io/network/esper/channel/kitteh.org/logs/2016/02/07/#L14

**Comment by lol768** [comment]
This is better handled by the IRC v3 guys as an extension to the STS work.

**Comment by mbax** [comment]
ok
