### ISSUE TITLE
Support IRCv3.2 batch extension

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#51]
http://ircv3.net/specs/extensions/batch-3.2.html

**Comment by lol768** [comment]
Ideas for implementation, would appreciate any thoughts:

* Modify [IRCServerMessage](https://github.com/KittehOrg/KittehIRCClientLib/blob/master/src/main/java/org/kitteh/irc/client/library/implementation/IRCServerMessage.java) to add a getBatchIdentifier()/getBatchReference() method which returns a String. Not sure whether the IRCServerMessage class should handle figuring out the batch reference itself (i.e. look at the tags in the constructor and set a private field - IMO this violates the SRP) or have the batch identifier passed in via the constructor.
    * Need to consider whether we should remove the batch tag from the `List<MessageTag> tags` field. IMO it should be left there in case users want to do additional processing on the raw tags.
* Add new events, BatchStartEvent and BatchEndEvent. These could probably benefit from an abstract BatchEvent to extend from. They need to provide a way to get the batch reference String. The BatchStartEvent also should expose the batch type and its parameters.
    * Alternatively (and this might be a nicer approach) we could create a new Batch class to store:
        * The batch identifier/reference
        * The batch type
        * The batch parameters
    * This entity would then be exposed from all `BatchEvent` subclasses. We could also make it available from the `IRCServerMessage` class instances. We'd need a way to lookup Batch objects based on their reference. We could just store them in an array and do a linear search each time (yay O(n)) or use the sensible approach and have a Map<String, Batch> where the key is the batch reference.
        * Need to consider what happens when we have multiple batches with the same identifier but different parameters. Should we just remove a batch from the map after it's ended?
    * We could subclass the `Batch` class and provide classes for the batch types defined in the spec. E.g. `NetsplitBatch` and `NetjoinBatch`
