### ISSUE TITLE
Support IRCv3.2 chghost extension

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#52]
http://ircv3.net/specs/extensions/chghost-3.2.html

**Comment by lol768** [comment]
Thoughts on new `UserChangeHostEvent`?

* `getUser()` (unless we get something like this method for free by extending another class)
* `getChangeType()` returns enum type explaining what was changed:
    * HOST, USER, BOTH
* Might want methods to `getNewHost()` or `getNewUser()` or `getOldHost()` etc?

**Comment by mbax** [comment]
Sounds good. Would there be separate user/host events or one event to match one `ServerMessage`?

**Comment by lol768** [comment]
Not sure, to be honest. The one event would need the annoying getters, though we could perhaps simplify it:

* getHost() => returns some object with getOld() and getNew() methods.
* getUser() => returns some object with getOld() and getNew() methods.

Two separate methods are nicer for subscribing to *just* user changes or *just* host changes.

**Comment by mbax** [comment]
UserInfoChangeEvent with various Optional getters for various changes which, if present, supply the new/old data?

```java
interface ChangedData<Type> {
    Type getNew();
    Type getOld();
}

UserInfoChangeEvent {
    Optional<ChangedData<String>> getHost();
    // etc
}
```

**Comment by lol768** [comment]
And where not present, there hasn't been a change?

That works for me.

**Comment by mbax** [comment]
Yeah, present only if changed. Include changes to nick, account, userstring, host... etc?

Alternatively, for real fun:

Interface events for all the changes, and combo-classes for when a change happens to more than one, so that you can listen to a particular change and if it's a change to multiple your multiple listeners all get the same event.

**Comment by lol768** [comment]
Should I update org.kitteh.irc.client.library.event.helper.ChannelUserListChange.Change and have the new event implement org.kitteh.irc.client.library.event.helper.ChannelUserListChange?

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/38c18fd012a39a4ab0eb572f9d2505ecd3824fa9
