### ISSUE TITLE
Reach high code coverage

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#62]
[![codecov.io](http://codecov.io/github/KittehOrg/KittehIRCClientLib/coverage.svg?branch=master)](http://codecov.io/github/KittehOrg/KittehIRCClientLib?branch=master)

**Comment by jkcclemens** [comment]
fwiw, I think that [shields.io](http://shields.io/)'s codecov badge is better. It says "Coverage" instead of "Codecov" and is a standardized badge.

**Comment by mbax** [comment]
Neat, thanks!

**Comment by lol768** [comment]
Define "high"

**Comment by jkcclemens** [comment]
high af

**Comment by mbax** [comment]
https://www.youtube.com/watch?v=DhAFbwoaH7o

**Comment by mbax** [comment]
I've decided I don't like this being an issue. Closing in favor of some day doing something about it.
