### ISSUE TITLE
Remove NICK_CHANGE, stop UserNickChangeEvent impl ChannelUserListChange

### ISSUE THREAD

**Issue by lol768** [KittehOrg/KittehIRCClientLib#67]
Context: https://korobi.io/network/esper/channel/kitteh.org/logs/2015/11/08/#L36-50

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/38c18fd012a39a4ab0eb572f9d2505ecd3824fa9
