### ISSUE TITLE
SASL EXTERNAL support?

### ISSUE THREAD

**Issue by lol768** [KittehOrg/KittehIRCClientLib#71]
Not possible with current API structure - there is no authline to base64 nor a password

```irc
<lol768> so for the client, does it just send "AUTHENTICATE EXTERNAL", "AUTHENTICATE +"?
<amdj> I believe so.
```

Probably post v1.

**Comment by lol768** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/f7f383573dd994adb832ef98aad893b62d143b3a

**Comment by lol768** [comment]
@mbax Does this need testing?

**Comment by mbax** [comment]
Aaaaaaaabsolutely.
