### ISSUE TITLE
Add ability to KNOCK on a channel

### ISSUE THREAD

**Issue by lol768** [KittehOrg/KittehIRCClientLib#74]
Seems we have an event for this but not a method to do the KNOCKing?

Would basically do:

```java
this.sendRawLine("KNOCK #heavens-door");
```

Would add to org.kitteh.irc.client.library.Client? Or would you see this more as an unnecessary convenience method?

**Comment by mbax** [comment]
Client#knockChannel(String) seems alright.

**Comment by lol768** [comment]
6fd85d0e5aae0fe6d5646be96b40d713f77830d6
