### ISSUE TITLE
Toggle for CAP LS on connect

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#80]
Dinosaur networks (example here is synirc) disconnect you for such things.

**Comment by lol768** [comment]
`ClientBuilder#setCapLsEnabled(boolean value)`? `ClientBuilder#capSettings()` with `disableCapLsOnConnect()` or `setCapLsEnabled(boolean value)`?

**Comment by mbax** [comment]
HAHA DISREGARD THIS I SUCK
