### ISSUE TITLE
KICL doesn't like ZNC disconnect/connect

### ISSUE THREAD

**Issue by kenzierocks** [KittehOrg/KittehIRCClientLib#86]
KICL throws errors when ZNC reconnects: https://gist.github.com/kenzierocks/346d841b60058344b850.

**Comment by mbax** [comment]
Suspicion: Has parted all channels prior to this happening. Can you confirm that, @kenzierocks ?

**Comment by kenzierocks** [comment]
Maybe, if znc parts you when it disconnects from IRC.

**Comment by mbax** [comment]
Do you happen to have the messages from the server logged when this happened?

**Comment by mbax** [comment]
Per IRC discussion, appears resolved as of 0.3.10
