### ISSUE TITLE
WHOIS support

### ISSUE THREAD

**Issue by mbax** [KittehOrg/KittehIRCClientLib#87]
Some initial thoughts on data provided:
```java
public interface WhoisData {
    String getNick();
    String getUserString();
    String getHost();
    String getRealName();
    Map<String, Set<ChannelUserMode>> getChannels();
    Optional<String> getServer();
    Optional<String> getOperatorStatus();
    boolean getSecureConnection();
    Optional<String> getAccount();
}
```

**Comment by Zarthus** [comment]
getSecureConnection -> isSecureConnection

Sometimes idletime may be included as well, specifically when doing a server whois. Might be neat to include as an optional value?

Some users may be away. What about the away string?

**Comment by bendem** [comment]
Would there be a way to get the User instance from that?

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/6ae601e4f2f518ab9ac1f42cea323dbf8b85f839
