### ISSUE TITLE
MessageEvent or some sub-interface with getMessageReciever()

### ISSUE THREAD

**Issue by kenzierocks** [KittehOrg/KittehIRCClientLib#91]
Allows passing in a `ChannelMessageEvent` or `PrivateMessageEvent` to a function and easily sending back messages to the contextual area.

**Comment by mbax** [comment]
Perhaps:

```java
public interface MessageReceiverSenderEvent { // Alternate names: MessageReceiverEvent, MessageSenderEvent
    MessageReceiver getSender();
}
```

**Comment by mbax** [comment]
After discussion in IRC it was concluded this was pretty unnecessary.
