### ISSUE TITLE
Mark client as away

### ISSUE THREAD

**Issue by kashike** [KittehOrg/KittehIRCClientLib#98]
`Client#setAway(String)` to mark the `Client` as away, with ability to remove away status as well (`@Nullable`?)

**Comment by mbax** [comment]
Can't away status be revoked by various actions? Perhaps a command instead? Just a thought, not definite either way.

**Comment by kashike** [comment]
An `AwayCommand` would work, too, yes, and might be cleaner.

**Comment by mbax** [comment]
https://github.com/KittehOrg/KittehIRCClientLib/commit/69c8e9697a6e615422e0ff1ba932b9f1ec886950
